config/routes.rb
Rails.application.routes.draw do
  # root get 'homes/index'

   devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

      resources :reviews
      resources :services do
        resources :reviews, only: [:new, :create]
      end
      get 'search', to: 'reviews#location_service_name'
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :reviews
  enum status: { Open: 'Open', Close: 'Close' }
  validates :service_name, :status, :location, :city, presence: true
  has_one_attached :service_profile
  def self.ransackable_attributes(auth_object = nil)
    ["city", "created_at", "id", "location", "service_name","avg_rating" "status", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["reviews", "user"]
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # before_action :require_admin
  # load_and_authorize_resource


  def index
    @services = Service.all
  end
  def show
    @service = Service.find(params[:id])
  end
  def new
    @service = Service.new
  end

  def create
   @service =Service.new(service_params)
   @service.user = current_user
    if@service.save
      redirect_to services_path
    else
      render :new
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
   @service = current_user.services.find_by_id(params[:id])
    if @service.present?
      @service.update(service_params)
      redirect_to services_path
    else
      # render :edit
      flash[:notice]= "you con't update another Admins service.ss"
      redirect_to services_path
    end
  end

  def destroy
    @service = current_user.services.find_by_id(params[:id])
    if @service.present?
      @service.delete
      redirect_to services_path
    else
      flash[:notice]="you con't delete another Admin service."
      redirect_to services_path
    end
  end

  private

  def service_params
    params.require(:service).permit(:service_name, :status ,:location, :city, :user_id,:service_profile)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/edit.html.erb
<style>
  body {
       border: 1px solid #ccc;
      font-family: Arial, sans-serif;
      display: flex;
      justify-content: center;
      background: grey;
      align-items: center;
      min-height: 100vh;
      color: white;
      margin: 0;
    }
section
{
  position: absolute;
  width: 100vw;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 2px;
  flex-wrap: wrap;
  overflow: hidden;
}


.signin
{
  position: absolute;
  width: 400px;
  color: black;
  background: #e9ecef;
  z-index: 1000;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 40px;
  border-radius: 4px;
  box-shadow: 0 15px 35px rgba(0,0,0,9);
}
h2
{
  font-size: 2em;
  text-transform: uppercase;
}

</style>
<div class="signin">
  <h2>Update Service</h2>
  <%= form_with model: @service do |form| %>
  <%= form.select :status, [["Open", "Open"], ["Close", "Close"]] %>
  <%= form.label :service_name %><br>
  <%= form.text_field :service_name %><br>

  <%= form.label :location %><br>
  <%= form.text_field :location %><br>

   <%= form.label :city %><br>
  <%= form.text_field :city %><br>

  <%= form.submit 'Update Service',class:"btn btn-outline-dark" %>
  <%= link_to "All Service", services_path,class:"btn btn-outline-dark" %>
  <% end %>
</div>
</div>
</section>

app/views/services/index.html.erb
<style type="text/css">
*{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
}
body{
    font-family: Helvetica;
    -webkit-font-smoothing: antialiased;
/*    background: rgba( 71, 147, 227, 1);*/
}
h2{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: black;
/*    padding: 30px 0;*/
}

/* Table Styles */

.table-wrapper{
    margin: 10px 70px 70px;
    box-shadow: 0px 35px 50px rgba( 0, 0, 0, 0.2 );
}

.fl-table {
    border-radius: 5px;
    font-size: 12px;
    font-weight: normal;
    border: none;
    border-collapse: collapse;
    width: 100%;
    max-width: 100%;
    white-space: nowrap;
    background-color: white;
}

.fl-table td, .fl-table th {
    text-align: center;
    padding: 8px;
}

.fl-table td {
    border-right: 1px solid #f8f8f8;
    font-size: 12px;
}

.fl-table thead th {
    color: #ffffff;
    background: #4FC3A1;
}


.fl-table thead th:nth-child(odd) {
    color: #ffffff;
    background: #324960;
}

.fl-table tr:nth-child(even) {
    background: #F8F8F8;
}
/*.footer{
  display: flex;
  align-items: center;
  justify-content: center;
  margin: -60px;
  background-color: white;
}*/
.footer {
/*  position: fixed;*/
/*   display: inline;*/
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: whitesmoke;
  color: white;
  padding-top: 15px;
/*  height: 50px;*/
}

.navbar-buttons {
  display: flex;
  gap: 10px;
}
.navbar-button {
  background-color: #4FC3A1;
  color: #FFFFFF;
  border: none;
  padding: 11px 12px;
  border-radius: 4px;
  text-decoration: none;
  cursor: pointer;
}
.navbar-button:hover {
  background-color: #27AE60;
}
h1{
    font-size: 10px;
    color: red;
}
.btn2{
/*    display: flex;*/
    margin-left: 480px;
/*    justify-content: center;*/
}
.ns{
/*    width: 50px;*/
margin-left: 340px;
/*margin-block: 20px;*/
margin-block: -38px;
}
</style>
<h1><%=flash[:notice]%></h1>
<h2>All Services</h2>
<div class="table-wrapper">
    <table class="fl-table">
        <thead>
        <tr>
           <th>picture</th>
           <th>Status</th>
           <th>service_name</th>
           <th>location</th>
           <th>city</th>
           <th>avg_rating</th>
           <th>user_id</th>
           <th>service_id</th>
           <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>
        <%@services.each do |service| %>
      <tr>
        <%if service.service_profile.attached? %>
        <td> <%= image_tag service.service_profile, :style => "max-height:40px" %> </td>
        <%end %>
        <td><%= service.status %></td>
        <td><%= service.service_name %></td>
        <td><%= service.location %></td>
        <td><%= service.city %></td>
        <td><%= service.avg_rating %></td>
        <td><%= service.user_id %></td>
        <td><%= service.id %></td>
        <td><%= link_to "Edit", edit_service_path(service),class:'navbar-button'%></td>
        <td><%= button_to "Destroy", service, method: :delete,class:'navbar-button'%></td>
      </tr>
    <% end %>
        <tbody>
    </table>
</div>
<div class= "btn2"><%= button_to "logout", destroy_user_session_path ,method: :delete, class:'btn btn-outline-dark'%>
</div>
<div class="ns"> <%= link_to "New Service", new_service_path, method: :get,  class:'btn btn-outline-dark' %>
 </div>

  </div>

app/views/services/new.html.erb
<style>
  body {
       border: 1px solid #ccc;
      font-family: Arial, sans-serif;
      display: flex;
      justify-content: center;
      background: grey;
      align-items: center;
      min-height: 100vh;
      color: white;
      margin: 0;
    }
.signin
{
  position: absolute;
  width: 400px;
  color: black;
  background: #e9ecef;
  z-index: 1000;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 40px;
  border-radius: 4px;
  box-shadow: 0 15px 35px rgba(0,0,0,9);
}
section .signin .content
{
  position: relative;
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  gap: 40px;
}
 h2
{
  font-size: 2em;
  text-transform: uppercase;
}
</style>

<div class="signin">
  <div class="content">
  <h2>Create Service</h2>
  <%= form_with model: @service do |form| %>
  <%= form.select :status, [["Open", "Open"], ["Close", "Close"]] %>
  <%= form.label :service_name %><br>
  <%= form.text_field :service_name %><br>

  <%= form.label :location %><br>
  <%= form.text_field :location %><br>

   <%= form.label :city %><br>
  <%= form.text_field :city %><br>

  <%= form.label :service_profile %>
  <%= form.file_field :service_profile %><br>

  <%= form.submit 'create service',class:"btn btn-outline-dark" %>
  <%= link_to "All Service", services_path,class:"btn btn-outline-dark"%>

  <% end %>

</div>
</div>
</section>

app/views/services/show.html.erb
<style type="text/css">
*{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
}
body{
    font-family: Helvetica;
    -webkit-font-smoothing: antialiased;
/*    background: rgba( 71, 147, 227, 1);*/
}
h2{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: black;
    padding: 30px 0;
}

/* Table Styles */

.table-wrapper{
    margin: 10px 70px 70px;
    box-shadow: 0px 35px 50px rgba( 0, 0, 0, 0.2 );
}

.fl-table {
    border-radius: 5px;
    font-size: 12px;
    font-weight: normal;
    border: none;
    border-collapse: collapse;
    width: 100%;
    max-width: 100%;
    white-space: nowrap;
    background-color: white;
}

.fl-table td, .fl-table th {
    text-align: center;
    padding: 8px;
}

.fl-table td {
    border-right: 1px solid #f8f8f8;
    font-size: 12px;
}

.fl-table thead th {
    color: #ffffff;
    background: #4FC3A1;
}


.fl-table thead th:nth-child(odd) {
    color: #ffffff;
    background: #324960;
}

.fl-table tr:nth-child(even) {
    background: #F8F8F8;
}
.footer{
  display: flex;
  align-items: center;
  justify-content: center;
  margin: -60px;
  background-color: white;
}
.li{
  display: flex;
  align-items: center;
  justify-content: center;
}


</style>

<h2> Service</h2>
<div class="table-wrapper">
    <table class="fl-table">
        <thead>
        <tr>
           <th>service_name</th>
           <th>city</th>
           <th>status</th>
           <th>location</th>
           <th>user_id</th>
           <th>picture</th>

           <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>
          <td><%= @service.service_name %></td>
          <td><%= @service.city %></td>
          <td><%= @service.status %></td>
          <td><%= @service.location %></td>
         <td><%= @service.user_id %></td>
         <td> <%= image_tag @service.service_profile, :style => "max-height:40px" %></td>

      </tr>
        <tbody>
    </table>
</div>
<div class="li">
   <%= link_to "All Service", services_path %>
</div>