config/routes.rb
Rails.application.routes.draw do
  # root get 'homes/index'

   devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

      resources :reviews
      resources :services do
        resources :reviews, only: [:new, :create]
      end
      get 'search', to: 'reviews#location_service_name'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # load_and_authorize_resource
def index
    @reviews= Review.all
  end
  def new
    if params[:service_id]
      @service = Service.find(params[:service_id])
      @review = @service.reviews.new
    else
      @services = Service.all
    end
    @review = Review.new
  end

   def show
    @review = Review.find(params[:id])
  end

  def create
    @service = Service.find(params[:review][:service_id])
    @review = @service.reviews.new(review_params)
    @review.user = current_user
    if @review.save
     redirect_to reviews_path,notice: "Review Creted successfully."
    else
     render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end
  def update
    @review = current_user.reviews.find_by_id(params[:id])

    if @review.present?
      @review.update(review_params)
      redirect_to reviews_path
    else
      redirect_to reviews_path, notice: "you con't update another users's review."
    end
  end

  def destroy
    @review = current_user.reviews.find_by_id(params[:id])
    if @review.present?
      @review.delete
      redirect_to reviews_path, notice: "Review deleted successfully."
    else
      redirect_to reviews_path, notice: "you con't delete another users's review."
    end
  end

  def location_service_name
    if  params[:service_name].present?
      @services = Service.where("service_name like ?" ,"%#{params[:service_name]}%")
      if @services.present?
      render 'service_name_print'
    else
      redirect_to reviews_path, notice: "Service Not Exits "
    end
    elsif params[:city].present?
      @services = Service.where("city like ?" ,"%#{params[:city]}%")
       if @services.present?
        render 'reviews/service_name_print'
      else
        redirect_to reviews_path ,notice: "Service Not Exits For This City"
      end

      elsif params[:status].present?
      @services = Service.where("status like ?" ,"%#{params[:status]}%")
       if @services.present?
        render 'reviews/service_name_print'
      else
        redirect_to reviews_path ,notice: "Service Not Exits For This status"
      end
    elsif params[:avg_rating].present?
      @services = Service.where("avg_rating like ?" ,"%#{params[:avg_rating]}%")
       if @services.present?
        render 'reviews/service_name_print'
      else
        @services = Service.order(avg_rating: :desc)
        render 'reviews/service_name_print'
      end

    elsif current_user.present?
      @services = Service.where(location: current_user.location)
      if @services.present?
        render 'service_name_print'
      else
        services = Service.all
        redirect_to services_path
      end
  end
end
  private
  def review_params
    params.require(:review).permit(:content, :rating, :service_id)

  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<style type="text/css">
{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
}
body{
    font-family: Helvetica;
    -webkit-font-smoothing: antialiased;
/*    background: darkblue;*/

}
.as{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: white;
    padding: 30px 0;
}
h1{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
    padding: 30px 0;
    color: white;
}
.btn{
  margin-top: 5px;
  padding: 2px;
  color: white;
  margin-left: 10px;
}

/* Table Styles */

.table-wrapper{
    margin: 10px 70px 70px;
    background: lightskyblue;
    box-shadow: 0px 35px 50px rgba( 0, 0, 0, 0.2 );
}
.form{
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>

  <div class="table-wrapper bg-secondary">
  <h1> Update Review</h1>
  <div class="form text-white">
      <%= form_with model: @review do |form| %>
      <%= form.label :rating %><br>
      <%= form.number_field :rating %><br>
      <%= form.label :content%><br>
      <%= form.text_field :content %><br>
      <%= form.submit 'Edit Review',class:"btn btn-outline-dark " %>
       <% end %>
</div>
  <div class="as">
    <%= link_to "All Review", reviews_path,class:"btn btn-outline-dark" %>
  </div>
</div>

app/views/reviews/index.html.erb
<style type="text/css">
{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
}
body{
    font-family: Helvetica;
    -webkit-font-smoothing: antialiased;

}
.as{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: white;
    padding: 30px 0;
}
.btn{
  margin: 2px;
}
h1{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
/*    background: linear-gradient(#000,#0f0,#000);*/
    padding: ;
}

/* Table Styles */

.table-wrapper{
    margin: 10px 70px 70px;
    box-shadow: 0px 35px 50px rgba( 0, 0, 0, 0.2 );
}

.fl-table {
    border-radius: 5px;
    font-size: 12px;
    font-weight: normal;
    border: none;
    border-collapse: collapse;
    width: 100%;
    max-width: 100%;
    white-space: nowrap;
    background-color: white;
}

.fl-table td, .fl-table th {
    text-align: center;
    padding: 8px;
}

.fl-table td {
    border-right: 1px solid #f8f8f8;
    font-size: 12px;
/*    background: green;*/
}

.fl-table thead th {
    color: #ffffff;
    background: #4FC3A1;
}


.fl-table thead th:nth-child(odd) {
    color: #ffffff;
    background: #324960;
}

.fl-table tr:nth-child(even) {
    background: #F8F8F8;
}
.footer{
  display: flex;
  align-items: center;
  justify-content: center;
  margin: -60px;
  background-color: white;
}
.form1{
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 10px;
}
.form{
/*  margin-top: 20px;*/
  display: flex;
  color: black;
  align-items: center;
  justify-content: center;
  border: 2px solid black;
  background-color: #e9ecef;;
}
.footer {
  display: flex;
  align-items: center;
  justify-content: center;
}

.navbar-buttons {
  display: flex;
  gap: 10px;
}
.navbar-button {
/*  background-color: #919fad;*/
  background-color: white;
  border: 2px solid red;
  color: black;
  border: none;
  padding: 2px 12px;
  border-radius: 4px;
  text-decoration: none;
  text-align: center;
  cursor: pointer;
  margin-top: 4px;
  margin-left: 56px
}

.navbar-button:hover {
  background-color: #324960;
}

</style>

  <div class="table-wrapper">

<h1>All Reviews</h1>
<table class="fl-table">
  <thead>
    <tr>
      <th>review_id</th>
      <th>service_id</th>
       <th>user_id</th>
      <th>Rating </th>
      <th>content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%@reviews.each do |review| %>
      <tr>
        <td><%= review.id %></td>
        <td><%= review.service_id%></td>
        <td><%= review.user_id%></td>
        <td><%= review.rating %></td>
        <td><%= review.content %></td>
        <td><%= link_to "Edit", edit_review_path(review),class:"btn btn-outline-dark"%></td>
         <td><%= button_to "Destroy", review, method: :delete,class:"btn btn-outline-dark"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<div class="form1">
  <%= link_to "New Review", new_review_path,class:"btn btn-outline-dark" %>
<%= button_to "logout", destroy_user_session_path, method: :delete,class:"btn btn-outline-dark"%>
</div>

<div class="form">
<h1>Search Services </h1>
</div>
<div class="form">
<%= form_with url:search_path, method: :get do |form| %><br>
<h1>Search Services </h1>
  <%= form.label :service_name %><br>
  <%= form.text_field :service_name %><br>

  <%= form.label :status %><br>
  <%= form.text_field :status %><br>
  <%= form.label :avg_rating %><br>
  <%= form.text_field :avg_rating %><br>

  <%= form.label :city %><br>
  <%= form.text_field :city %><br>
   <%= form.submit 'Search',class:"navbar-button" %>
<% end %>
</div>
</div>

app/views/reviews/new.html.erb
<style type="text/css">
{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
}
body{
    font-family: Helvetica;
    -webkit-font-smoothing: antialiased;

}
.as{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: white;
    padding: 30px 0;
}
h1{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
}

/* Table Styles */

.table-wrapper{
    margin: 10px 70px 70px;
    box-shadow: 0px 35px 50px rgba( 0, 0, 0, 0.2 );
}

.fl-table {
    border-radius: 5px;
    font-size: 12px;
    font-weight: normal;
    border: none;
    border-collapse: collapse;
    width: 100%;
    max-width: 100%;
    white-space: nowrap;
    background-color: white;
}

.fl-table td, .fl-table th {
    text-align: center;
    padding: 8px;
}

.fl-table td {
    border-right: 1px solid #f8f8f8;
    font-size: 12px;
}

.fl-table thead th {
    color: #ffffff;
    background: #4FC3A1;
}


.fl-table thead th:nth-child(odd) {
    color: #ffffff;
    background: #324960;
}

.fl-table tr:nth-child(even) {
    background: #F8F8F8;
}
.footer{
  display: flex;
  align-items: center;
  justify-content: center;
  margin: -60px;
  background-color: white;
}

</style>



<!-- <div class="table-wrapper"> -->
  <div>
    <% if @service %>
  <h1 > create review for <%= @service.service_name %></h1>
  <%= render 'form' %>
  <%else %>
  </div>
  <div class="table-wrapper">
  <h1> Select Service For Review</h1>
  <ul>

  <table class="fl-table">
    <thead>
      <tr>
        <th>Status</th>
        <th>service_name</th>
        <th>location</th>
        <th>city</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%@services.each do |service| %>
        <tr>
          <td><%= service.status %></td>
          <td><%= service.service_name %></td>
          <td><%= service.location %></td>
          <td><%= service.city %></td>
          <td><%= link_to service.service_name, new_review_path(service_id: service.id),class:"btn btn-outline-dark"%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="as">
    <%= link_to "All Review", reviews_path,class:"btn btn-outline-dark" %>
  </div>

</div>
  <%end %>

app/views/reviews/service_name_print.html.erb
<style>
.table-wrapper{
    margin: 10px 70px 70px;
    box-shadow: 0px 35px 50px rgba( 0, 0, 0, 0.2 );
}

.fl-table {
    border-radius: 5px;
    font-size: 12px;
    font-weight: normal;
    border: none;
    border-collapse: collapse;
    width: 100%;
    max-width: 100%;
    white-space: nowrap;
    background-color: white;
}

.fl-table td, .fl-table th {
    text-align: center;
    padding: 8px;
}

.fl-table td {
    border-right: 1px solid #f8f8f8;
    font-size: 12px;
}

.fl-table thead th {
    color: #ffffff;
    background: #4FC3A1;
}


.fl-table thead th:nth-child(odd) {
    color: #ffffff;
    background: #324960;
}

.fl-table tr:nth-child(even) {
    background: #F8F8F8;
}
.footer {
/*  position: fixed;*/
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: whitesmoke;
  color: white;
  text-align: center;
/*  padding-top: 22px;*/
  height: 28px;
  margin-bottom: 17px;
}

.navbar-buttons {
  display: flex;
  gap: 10px;
}
.navbar-button {
  background-color: #4FC3A1;
  color: #FFFFFF;
  border: none;
  padding: 5px 12px;
  border-radius: 4px;
  text-decoration: none;
  cursor: pointer;
  margin-top: 20px;
}
.navbar-button:hover {
  background-color: #27AE60;
}

.btn2{
/*    display: flex;*/
    margin-left: 480px;
/*    justify-content: center;*/
}
.ns{
/*    width: 50px;*/
margin-left: 340px;
/*margin-block: 20px;*/
margin-block: -38px;
}
</style>



<div class="table-wrapper">
<table class="fl-table">
  <thead>
    <tr>
      <th>Status    |</th>
      <th>service_name         |</th>
      <th>location        |</th>
      <th>city</th>
      <th>avg_rating</th>
      <th>user_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <%@services.each do |service| %>
      <tr>
        <td><%= service.status %></td>
        <td><%= service.service_name %></td>
        <td><%= service.location %></td>
        <td><%= service.city %></td>
        <td><%= service.avg_rating %></td>
        <td><%= service.user_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<div class= "btn2"><%= button_to "logout", destroy_user_session_path ,method: :delete, class:'btn btn-outline-dark'%>
</div>
<div class="ns"> <%= link_to "All Review",reviews_path, method: :get,  class:'btn btn-outline-dark' %>
 </div>

app/views/reviews/show.html.erb
<style type="text/css">
{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
}
body{
    font-family: Helvetica;
    -webkit-font-smoothing: antialiased;
/*    background: rgba( 71, 147, 227, 1);*/
/*  background: linear-gradient(#000,#0f0,#000);*/

}
.as{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: white;
    padding: 30px 0;
}
h1{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
/*    background: linear-gradient(#000,#0f0,#000);*/
    padding: ;
}

/* Table Styles */

.table-wrapper{
    margin: 10px 70px 70px;
    box-shadow: 0px 35px 50px rgba( 0, 0, 0, 0.2 );
}

.fl-table {
    border-radius: 5px;
    font-size: 12px;
    font-weight: normal;
    border: none;
    border-collapse: collapse;
    width: 100%;
    max-width: 100%;
    white-space: nowrap;
    background-color: white;
}

.fl-table td, .fl-table th {
    text-align: center;
    padding: 8px;
}

.fl-table td {
    border-right: 1px solid #f8f8f8;
    font-size: 12px;
/*    background: green;*/
}

.fl-table thead th {
    color: #ffffff;
    background: #4FC3A1;
}


.fl-table thead th:nth-child(odd) {
    color: #ffffff;
    background: #324960;
}

.fl-table tr:nth-child(even) {
    background: #F8F8F8;
}
.footer{
  display: flex;
  align-items: center;
  justify-content: center;
  margin: -60px;
  background-color: white;
}
.form{
  display: flex;
  align-items: center;
  justify-content: center;
}

</style>

  <div class="table-wrapper">
<table class="fl-table">
  <thead>
    <tr>
      <th>review_id     |</th>
      <th>service_id    |</th>
       <th>user_id      |</th>
      <th>Rating        |</th>
      <th>content       |</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @review.id %></td>
        <td><%= @review.service_id%></td>
        <td><%= @review.user_id%></td>
        <td><%= @review.rating %></td>
        <td><%= @review.content %></td>

      </tr>
  </tbody>
</table>
<br>
<div class="form">
  <%= link_to "New Review", new_review_path %>||
  <%= link_to "All Review", reviews_path %>
</div>
</div>
</div>